kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-website
  labels:
    app: {{ .Release.Name }}-website
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{ if .Values.cdash.https }}
  tls:
    - secretName: "{{ .Release.Name }}-tls"
      hosts:
        - {{ .Values.cdash.host }}
  {{ end }}
  rules:
    - host: {{ .Values.cdash.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-website
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
