cdash:
  # cdash.host is the host name for CDash.
  host: cdash-example.local

  # cdash.https controls whether the CDash external URL
  # uses https instead of http.
  # When using https for a production CDash server, you should
  # also create a Kubernetes TLS secret named "<release name>-tls"
  # https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls/
  https: true

  # cdash.image is the Docker image to use for this CDash instance.
  image: "kitware/cdash:v4.5.0"

  # This Helm chart uses an embedded postgres database by default.
  # To use an external database instead, set postgresql.enabled: false
  # below and create a secret named '<release name>-db' with the following
  # values:
  # - host (required)
  # - password (required)
  # - username (optional, defaults to 'postgres')
  # - database (optional, defaults to 'cdash')

  # By default, this Helm chart uses an embedded MinIO for object storage.
  # To use AWS S3 instead, set minio.enabled: false below and create a secret
  # named '<release name>-s3' with the following values:
  # - accesskey
  # - secretkey
  # - region
  # - bucket

  # To securely store other other sensitive configuration data
  # (e.g. OAuth/email credentials) create a secret and name it here.
  # The keys of this secret need to match the names of the environment
  # variables that CDash expects.
  # https://github.com/Kitware/CDash/blob/master/docs/config.md
  externalSecret: ""

  # Optionally specify an existing serviceAccount for the cdash pods to use.
  serviceAccountName: default

  # cdash.env can be used to configure CDash by setting
  # additional environment variables.
  # https://github.com/Kitware/CDash/blob/master/docs/config.md
  env: |-
    #BACKUP_TIMEFRAME: 36

  website:
    resources:
      requests:
        memory: 256Mi

  worker:
    # cdash.worker.replicas controls how many worker pods
    # we should create for this Helm release.
    replicas: 1

    # Terminate (and restart) the worker pod *after* it parses
    # a submission if it consumes more than this amount of memory
    # (in megabytes).
    # This should probably match the memory request below.
    worker_memory: 256

    resources:
      requests:
        memory: 256Mi

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  ingressClassName: nginx

# This setting is necessary for us to be able to use
# the bitnamilegacy repository for postgres and minio.
global:
  security:
    allowInsecureImages: true

# See here for more config settings: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
postgresql:
  enabled: true
  image:
    repository: bitnamilegacy/postgresql
  auth:
    database: cdash
    existingSecret: "{{ .Release.Name }}-db"
    secretKeys:
      adminPasswordKey: password
  primary:
    persistence:
      # This is the size of the database's persistent volume.
      # Increase as necessary for your anticipated needs.
      size: "8Gi"

# See here for more config settings: https://github.com/bitnami/charts/tree/main/bitnami/minio
minio:
  enabled: true
  image:
    repository: bitnamilegacy/minio
  auth:
    existingSecret: "{{ .Release.Name }}-s3"
    rootPasswordSecretKey: secretkey
    rootUserSecretKey: accesskey
  defaultBuckets: cdash
  ingress:
    enabled: true
  persistence:
    annotations:
      helm.sh/resource-policy: keep
    # This is the size of the object store's persistent volume.
    # Increase as necessary for your anticipated needs.
    size: "8Gi"
